name: Nightly Build and Commit Trigger

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  push:
    branches:
      - main # or your main branch name (e.g., master)
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Default checkout path - should be /home/runner/work/ringworld

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            /usr/share
            /etc
          key: dependencies-ubuntu-latest # Simple cache key
          restore-keys: |
            dependencies-ubuntu-latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake mingw-w64 python3 lua5.3

      - name: Create build directory
        run: mkdir /home/runner/work/ringworld/build && cd /home/runner/work/ringworld/build # Absolute build dir

      - name: List SOURCE DIRECTORY contents
        run: ls -al /home/runner/work/ringworld # List contents of what CMake *should* see as source

      - name: Current Working Directory (pwd) - Before CMake
        run: pwd # Print CWD right before CMake

      - name: Generate build files
        run: cmake /home/runner/work/ringworld -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../toolchain-i686-w64-mingw32.cmake # Absolute source path, toolchain path relative to source

      - name: Build the project
        run: cmake --build .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ringworld-build-artifacts
          path: build # Artifacts will be in 'build' in /home/runner/work/ringworld
