name: Nightly Build and Commit Trigger

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  push:
    branches:
      - main # or your main branch name (e.g., master)
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Default checkout path - should be /home/runner/work/ringworld

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            /usr/share
            /etc
          key: dependencies-ubuntu-latest
          restore-keys: |
            dependencies-ubuntu-latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake mingw-w64 python3 lua5.3

      - name: Create build directory
        run: mkdir build && cd build # 'build' directory in /home/runner/work/ringworld

      - name: List ENTIRE WORKSPACE directory
        run: ls -al /home/runner/work # List EVERYTHING in /home/runner/work

      - name: Current Working Directory (pwd) - Before CMake
        run: pwd # Print CWD right before CMake

      - name: Generate build files (Simplified CMake command)
        run: cmake .. # Simplified cmake command - just source path

      - name: Build the project
        run: cmake --build .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ringworld-build-artifacts
          path: build # Artifacts in 'build' in /home/runner/work/ringworld
